<a href="https://colab.research.google.com/github/bik1111/pytorch-tutorial/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
torch.__version__

'2.1.0+cu121'

# **텐서 초기화와 데이터 타입**

초기화 되지 않은 텐서

In [4]:
x = torch.empty(4,2)
print(x)

tensor([[6.3897e-18, 4.3530e-41],
        [6.3897e-18, 4.3530e-41],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])


무작위로 초기화된 텐서

In [5]:
x = torch.rand(4,2)
print(x)

tensor([[0.7299, 0.3710],
        [0.5477, 0.3884],
        [0.8678, 0.9774],
        [0.1143, 0.1456]])


데이터 타입(dtype)이 long이고, 0으로 채워진 텐서

In [6]:
x = torch.zeros(4, 2, dtype = torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


사용자가 입력한 값으로 텐서 초기화

In [7]:
x = torch.tensor([4, 2, 2.3, 9.1])
x

tensor([4.0000, 2.0000, 2.3000, 9.1000])

2 x 4 크기, double 타입, 1로 채워진 텐서

In [8]:
x = x.new_ones(2, 4, dtype=torch.double)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

x와 같은 크기, float 타입, 무작위로 채워진 텐서

In [9]:
x = torch.rand_like(x, dtype = torch.float)
x

tensor([[0.0577, 0.0594, 0.5870, 0.1135],
        [0.9289, 0.0911, 0.4112, 0.6343]])

텐서 크기 계산

In [10]:
print(x.size())

torch.Size([2, 4])


# **데이터 타입 (Data Type)**

In [11]:
ft = torch.FloatTensor([1, 2, 3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


데이터 변환 (typeCasting)

In [12]:
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [13]:
it = torch.IntTensor([1, 2, 3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [14]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


# CUDA **Tensors**

- `.to` 메소드를 사용하여 텐서를 어떠한 장치(cpu,gpu)로 옮길 수 있음

In [15]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.0530])
-0.052998967468738556
torch.float32


In [16]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y = torch.ones_like(x, device = device)
print(y)
x = x.to(device)
print(x)
z = x + y
print(z)
print(z.to('cpu', torch.double))

cuda
tensor([1.], device='cuda:0')
tensor([-0.0530], device='cuda:0')
tensor([0.9470], device='cuda:0')
tensor([0.9470], dtype=torch.float64)


# **다차원 텐서 표현**

0D Tensor(Scalar)

- 하나의 숫자를 담고있는 텐서(tensor)
- 축과 형상이 없음

In [17]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


1D Tensor(Vector)

- 값들을 저장한 리스트와 유사한 텐서
- 하나의 축이 존재

In [18]:
t1 = torch.tensor([1, 2, 3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


2D Tensor(Matrix)
- 행렬과 같은 모양으로 두 개의 축이 존재
- 일반적인 수치, 통계 데이터셋에 해당
- 주로 샘플(samples)과 특성(features)을 가진 구조로 사용

In [19]:
t2 = torch.tensor([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


3D Tensor
- 큐브(cube)와 같은 모양으로 3개의 축이 존재
- 데이터가 연속된 시퀀스 데이터나 시간 축이 포함된 시계열 데이터에 해당
- 주식 가격 데이터셋, 시간에 따른 질병 발병 데이터 등이 존재
- 주로 샘플(samples), 타임스텝(timesteps), 특성(features)을 가진 구조로 사용

In [20]:
t3 = torch.tensor([[[1, 2, 3],
                   [4, 5, 6],
                    [7, 8, 9]],
                   [[1, 2, 3],
                   [4, 5, 6],
                    [7, 8, 9]],
                   [[1, 2, 3],
                   [4, 5, 6],
                    [7, 8, 9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


4D Tensor
- 4개의 축
- 컬러 이미지 데이터가 대표적인 사례(흑백 이미지 데이터는 3D Tensor로 가능)
- 주로 샘플(samples), 높이(height), 너비(width), 컬러 채널(channel)을 가진 구조로 사용

# **텐서의 연산(operations)**
- 텐서에 대한 수학 연산, 삼각 함수, 비트 연산, 비교 연산, 집계 등 제공

In [21]:
import math
a = torch.rand(1, 2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5)) #해당 범위로 찍어내린다.

tensor([[ 0.7834, -0.0230]])
tensor([[0.7834, 0.0230]])
tensor([[1., -0.]])
tensor([[ 0., -1.]])
tensor([[ 0.5000, -0.0230]])


In [22]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1, 2, 3, 1, 2, 2])))

tensor([[ 0.7834, -0.0230]])
tensor(-0.0230)
tensor(0.7834)
tensor(0.3802)
tensor(0.5702)
tensor(-0.0180)
tensor([1, 2, 3])


`max`와 `min`은 `dim` 인자를 줄 경우 argmax와 argmin도 함께 리턴

- argmax: 최대값을 가진 인덱스
- argmin: 최소값을 가진 인덱스

In [23]:
x = torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.2129, 0.2391],
        [0.8960, 0.6764]])
torch.return_types.max(
values=tensor([0.8960, 0.6764]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([0.2391, 0.8960]),
indices=tensor([1, 0]))


In [24]:
print(x)
print(x.min(dim=0))
print(x.min(dim=1))

tensor([[0.2129, 0.2391],
        [0.8960, 0.6764]])
torch.return_types.min(
values=tensor([0.2129, 0.2391]),
indices=tensor([0, 0]))
torch.return_types.min(
values=tensor([0.2129, 0.6764]),
indices=tensor([0, 1]))


In [25]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.2418, 0.2554],
        [0.1496, 0.9801]])
tensor([[0.3218, 0.2129],
        [0.7426, 0.2558]])


`torch.add` : 덧셈

In [26]:
print(x+y)
print(torch.add(x,y))

tensor([[0.5637, 0.4683],
        [0.8922, 1.2359]])
tensor([[0.5637, 0.4683],
        [0.8922, 1.2359]])


결과 텐서를 인자로 제공

In [27]:
result = torch.empty(2,4)
torch.add(x,y, out=result)
print(result)

tensor([[0.5637, 0.4683],
        [0.8922, 1.2359]])


<ipython-input-27-4be145b6d329>:2: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  torch.add(x,y, out=result)


`in-place` 방식

- in-place 방식으로 텐서의 값을 변경하는 연산 뒤에는 _"가 붙음
- x.copy_(y), x.t_()

In [28]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.2418, 0.2554],
        [0.1496, 0.9801]])
tensor([[0.3218, 0.2129],
        [0.7426, 0.2558]])
tensor([[0.5637, 0.4683],
        [0.8922, 1.2359]])


`torch.sub` : 뺄셈

In [29]:
print(x)
print(y)

print(x-y)
print(torch.sub(x,y))
print(x.sub(y))

tensor([[0.2418, 0.2554],
        [0.1496, 0.9801]])
tensor([[0.5637, 0.4683],
        [0.8922, 1.2359]])
tensor([[-0.3218, -0.2129],
        [-0.7426, -0.2558]])
tensor([[-0.3218, -0.2129],
        [-0.7426, -0.2558]])
tensor([[-0.3218, -0.2129],
        [-0.7426, -0.2558]])


`torch.mul` : 곱셈

In [30]:
print(x)
print(y)

print(x*y)
print(torch.mul(x,y))
print(x.mul(y))

tensor([[0.2418, 0.2554],
        [0.1496, 0.9801]])
tensor([[0.5637, 0.4683],
        [0.8922, 1.2359]])
tensor([[0.1363, 0.1196],
        [0.1335, 1.2113]])
tensor([[0.1363, 0.1196],
        [0.1335, 1.2113]])
tensor([[0.1363, 0.1196],
        [0.1335, 1.2113]])


`torch.div`: 나눗셈

In [32]:
print(x)
print(y)

print(x/y)
print(torch.div(x,y))
print(x.div(y))

tensor([[0.2418, 0.2554],
        [0.1496, 0.9801]])
tensor([[0.5637, 0.4683],
        [0.8922, 1.2359]])
tensor([[0.4290, 0.5454],
        [0.1677, 0.7930]])
tensor([[0.4290, 0.5454],
        [0.1677, 0.7930]])
tensor([[0.4290, 0.5454],
        [0.1677, 0.7930]])


`torch.mm`: 내적(dot product)

In [33]:
print(x)
print(y)

print(torch.matmul(x,y))
z = torch.mm(x,y)
print(z)
print(torch.svd(z))

tensor([[0.2418, 0.2554],
        [0.1496, 0.9801]])
tensor([[0.5637, 0.4683],
        [0.8922, 1.2359]])
tensor([[0.3642, 0.4289],
        [0.9588, 1.2813]])
tensor([[0.3642, 0.4289],
        [0.9588, 1.2813]])
torch.return_types.svd(
U=tensor([[-0.3313, -0.9435],
        [-0.9435,  0.3313]]),
S=tensor([1.6961, 0.0327]),
V=tensor([[-0.6045, -0.7966],
        [-0.7966,  0.6045]]))


## 텐서의 조작(Manipulations)
- 인덱싱(Indexing): Numpy처럼 인덱싱 형태로 사용가능

In [34]:
x = torch.Tensor([[1, 2],
                  [3, 4]])

print(x)

print(x[0,0])
print(x[0,1])
print(x[1,0])
print(x[1,1])

# 행은 다 선택하면서, 0번째 컬럼만 선택
print(x[:, 0])
print(x[:, 1])

print(x[0, :])
print(x[1, :])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([1., 3.])
tensor([2., 4.])
tensor([1., 2.])
tensor([3., 4.])


`view`: 텐서의 크기(size)나 모양(shape)을 변경
- 기본적으로 변경 전과 후에 텐서 안의 원소 갯수가 유지되어야 함
- -1 로 설정되면 계산을 통해 해당 크기값 유추

In [35]:
x = torch.randn(4,5)
print(x)

# x를 Flat하게 핀 상태
y = x.view(20)
print(y)

# 행은 5개 열은 알아서 조합(-1)
z = x.view(5, -1)
print(z)

tensor([[ 0.7564, -0.1327, -0.5587, -1.5017, -0.0843],
        [ 0.4174, -0.4371,  0.6720,  0.2246, -0.5086],
        [-0.7173,  1.7495,  0.2437, -0.2908, -1.7092],
        [-1.2189, -1.1885, -1.5630,  0.8562, -0.1116]])
tensor([ 0.7564, -0.1327, -0.5587, -1.5017, -0.0843,  0.4174, -0.4371,  0.6720,
         0.2246, -0.5086, -0.7173,  1.7495,  0.2437, -0.2908, -1.7092, -1.2189,
        -1.1885, -1.5630,  0.8562, -0.1116])
tensor([[ 0.7564, -0.1327, -0.5587, -1.5017],
        [-0.0843,  0.4174, -0.4371,  0.6720],
        [ 0.2246, -0.5086, -0.7173,  1.7495],
        [ 0.2437, -0.2908, -1.7092, -1.2189],
        [-1.1885, -1.5630,  0.8562, -0.1116]])


`item` : 텐서에 값이 단 하나라도 존재하면 숫자값을 얻을 수 있음
- 단, 스칼라값 하나만 존재해야 item() 사용 가능

In [37]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([1.1693])
1.1693092584609985
torch.float32


`squeeze`: 차원을 축소(제거)

In [38]:
tensor = torch.rand(1, 3, 3)
print(tensor)
print(tensor.shape)

tensor([[[0.1535, 0.1616, 0.7377],
         [0.8151, 0.1341, 0.4079],
         [0.4314, 0.3143, 0.4476]]])
torch.Size([1, 3, 3])


In [39]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[0.1535, 0.1616, 0.7377],
        [0.8151, 0.1341, 0.4079],
        [0.4314, 0.3143, 0.4476]])
torch.Size([3, 3])


`unsqueeze` : 차원을 증가 (생성)

In [40]:
t = torch.rand(3,3)
print(t)
print(t.shape)

tensor([[0.1999, 0.3524, 0.9013],
        [0.2908, 0.8650, 0.0655],
        [0.5581, 0.3892, 0.7816]])
torch.Size([3, 3])


In [41]:
tensor = t.unsqueeze(dim=0)
print(tensor)
print(tensor.shape)

tensor([[[0.1999, 0.3524, 0.9013],
         [0.2908, 0.8650, 0.0655],
         [0.5581, 0.3892, 0.7816]]])
torch.Size([1, 3, 3])


In [42]:
tensor = t.unsqueeze(dim=2)
print(tensor)
print(tensor.shape)

tensor([[[0.1999],
         [0.3524],
         [0.9013]],

        [[0.2908],
         [0.8650],
         [0.0655]],

        [[0.5581],
         [0.3892],
         [0.7816]]])
torch.Size([3, 3, 1])


`stack` : 텐서 간 결합

In [45]:
x = torch.FloatTensor([1,4])
print(x)
y = torch.FloatTensor([2,5])
print(y)
z = torch.FloatTensor([3, 6])

print(torch.stack([x,y,z]))

tensor([1., 4.])
tensor([2., 5.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
