In [2]:
import torch
torch.__version__

'2.1.0+cu121'

# **텐서 초기화와 데이터 타입**

초기화 되지 않은 텐서

In [3]:
x = torch.empty(4,2)
print(x)

tensor([[ 2.8026e-45,  0.0000e+00],
        [ 2.8026e-45,  7.0065e-45],
        [ 1.6381e-42,  4.3988e+21],
        [-2.6726e-22,  3.1060e-41]])


무작위로 초기화된 텐서

In [4]:
x = torch.rand(4,2)
print(x)

tensor([[0.0953, 0.9777],
        [0.7343, 0.8176],
        [0.5714, 0.7933],
        [0.0529, 0.8357]])


데이터 타입(dtype)이 long이고, 0으로 채워진 텐서

In [6]:
x = torch.zeros(4, 2, dtype = torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


사용자가 입력한 값으로 텐서 초기화

In [9]:
x = torch.tensor([4, 2, 2.3, 9.1])
x

tensor([4.0000, 2.0000, 2.3000, 9.1000])

2 x 4 크기, double 타입, 1로 채워진 텐서

In [11]:
x = x.new_ones(2, 4, dtype=torch.double)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

x와 같은 크기, float 타입, 무작위로 채워진 텐서

In [12]:
x = torch.rand_like(x, dtype = torch.float)
x

tensor([[0.3576, 0.9195, 0.4382, 0.1444],
        [0.3733, 0.8742, 0.2670, 0.7063]])

텐서 크기 계산

In [14]:
print(x.size())

torch.Size([2, 4])


# **데이터 타입 (Data Type)**

In [16]:
ft = torch.FloatTensor([1, 2, 3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


데이터 변환 (typeCasting)

In [17]:
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [19]:
it = torch.IntTensor([1, 2, 3])
print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [21]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


# CUDA **Tensors**

- `.to` 메소드를 사용하여 텐서를 어떠한 장치(cpu,gpu)로 옮길 수 있음

In [23]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.1021])
0.10211031138896942
torch.float32


In [28]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y = torch.ones_like(x, device = device)
print(y)
x = x.to(device)
print(x)
z = x + y
print(z)
print(z.to('cpu', torch.double))

cuda
tensor([1.], device='cuda:0')
tensor([0.1021], device='cuda:0')
tensor([1.1021], device='cuda:0')
tensor([1.1021], dtype=torch.float64)


# **다차원 텐서 표현**

0D Tensor(Scalar)

- 하나의 숫자를 담고있는 텐서(tensor)
- 축과 형상이 없음

In [31]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


1D Tensor(Vector)

- 값들을 저장한 리스트와 유사한 텐서
- 하나의 축이 존재

In [32]:
t1 = torch.tensor([1, 2, 3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


2D Tensor(Matrix)
- 행렬과 같은 모양으로 두 개의 축이 존재
- 일반적인 수치, 통계 데이터셋에 해당
- 주로 샘플(samples)과 특성(features)을 가진 구조로 사용

In [35]:
t2 = torch.tensor([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


3D Tensor
- 큐브(cube)와 같은 모양으로 3개의 축이 존재
- 데이터가 연속된 시퀀스 데이터나 시간 축이 포함된 시계열 데이터에 해당
- 주식 가격 데이터셋, 시간에 따른 질병 발병 데이터 등이 존재
- 주로 샘플(samples), 타임스텝(timesteps), 특성(features)을 가진 구조로 사용

In [36]:
t3 = torch.tensor([[[1, 2, 3],
                   [4, 5, 6],
                    [7, 8, 9]],
                   [[1, 2, 3],
                   [4, 5, 6],
                    [7, 8, 9]],
                   [[1, 2, 3],
                   [4, 5, 6],
                    [7, 8, 9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


4D Tensor
- 4개의 축
- 컬러 이미지 데이터가 대표적인 사례(흑백 이미지 데이터는 3D Tensor로 가능)
- 주로 샘플(samples), 높이(height), 너비(width), 컬러 채널(channel)을 가진 구조로 사용

# **텐서의 연산(operations)**
- 텐서에 대한 수학 연산, 삼각 함수, 비트 연산, 비교 연산, 집계 등 제공

In [43]:
import math
a = torch.rand(1, 2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5)) #해당 범위로 찍어내린다.

tensor([[-0.6045,  0.7951]])
tensor([[0.6045, 0.7951]])
tensor([[-0., 1.]])
tensor([[-1.,  0.]])
tensor([[-0.5000,  0.5000]])


In [45]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1, 2, 3, 1, 2, 2])))

tensor([[-0.6045,  0.7951]])
tensor(-0.6045)
tensor(0.7951)
tensor(0.0953)
tensor(0.9897)
tensor(-0.4807)
tensor([1, 2, 3])


`max`와 `min`은 `dim` 인자를 줄 경우 argmax와 argmin도 함께 리턴

- argmax: 최대값을 가진 인덱스
- argmin: 최소값을 가진 인덱스

In [47]:
x = torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.0381, 0.3693],
        [0.9864, 0.2075]])
torch.return_types.max(
values=tensor([0.9864, 0.3693]),
indices=tensor([1, 0]))
torch.return_types.max(
values=tensor([0.3693, 0.9864]),
indices=tensor([1, 0]))


In [48]:
print(x)
print(x.min(dim=0))
print(x.min(dim=1))

tensor([[0.0381, 0.3693],
        [0.9864, 0.2075]])
torch.return_types.min(
values=tensor([0.0381, 0.2075]),
indices=tensor([0, 1]))
torch.return_types.min(
values=tensor([0.0381, 0.2075]),
indices=tensor([0, 1]))


In [49]:
x = torch.rand(2,2)
print(x)
y = torch.rand(2,2)
print(y)

tensor([[0.0548, 0.5762],
        [0.2393, 0.0856]])
tensor([[0.9149, 0.9060],
        [0.5372, 0.4028]])


`torch.add` : 덧셈

In [50]:
print(x+y)
print(torch.add(x,y))

tensor([[0.9696, 1.4823],
        [0.7765, 0.4884]])
tensor([[0.9696, 1.4823],
        [0.7765, 0.4884]])


결과 텐서를 인자로 제공

In [52]:
result = torch.empty(2,4)
torch.add(x,y, out=result)
print(result)

tensor([[0.9696, 1.4823],
        [0.7765, 0.4884]])


<ipython-input-52-4be145b6d329>:2: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  torch.add(x,y, out=result)


`in-place` 방식

- in-place 방식으로 텐서의 값을 변경하는 연산 뒤에는 _"가 붙음
- x.copy_(y), x.t_()

In [54]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.0548, 0.5762],
        [0.2393, 0.0856]])
tensor([[0.9149, 0.9060],
        [0.5372, 0.4028]])
tensor([[0.9696, 1.4823],
        [0.7765, 0.4884]])


`torch.sub` : 뺄셈

In [57]:
print(x)
print(y)

print(x-y)
print(torch.sub(x,y))
print(x.sub(y))

tensor([[0.0548, 0.5762],
        [0.2393, 0.0856]])
tensor([[0.9696, 1.4823],
        [0.7765, 0.4884]])
tensor([[-0.9149, -0.9060],
        [-0.5372, -0.4028]])
tensor([[-0.9149, -0.9060],
        [-0.5372, -0.4028]])
tensor([[-0.9149, -0.9060],
        [-0.5372, -0.4028]])
